"""Load and (re)generate the reviewed entity crosswalk YAML. The I/O half of FSC-23.

The crosswalk *logic* is pure and lives in ``core.crosswalk``; this module is the only place that
touches the file. It mirrors ``registry.py``: a default path under ``data/crosswalk/`` with a
``CFP_CROSSWALK_PATH`` env override for non-editable installs. Loading fails loud — a malformed
SIREN, a broken status<->SIREN invariant, or a conflicting-key collision all raise.
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path
from typing import Any

import yaml
from core.crosswalk import Crosswalk, CrosswalkEntry, CrosswalkStatus

SCHEMA_VERSION = 1

# The single source of truth for "human curation we must never clobber on re-seed". Shared by
# merge_seed and the CLI's preserved-count so the two can never drift.
CURATED_STATUSES: frozenset[CrosswalkStatus] = frozenset(
    {CrosswalkStatus.reviewed, CrosswalkStatus.category}
)

# Written at the top of the generated file so it stays self-describing across regenerations
# (yaml.safe_dump drops comments, so this header is re-emitted each time, not hand-maintained).
_HEADER = (
    "# Reviewed crosswalk: name -> SIREN for entities lacking one (golden rule #5).\n"
    "# `auto`/`pending` rows are GENERATED by `make resolve-seed` (re-seedable, merge-aware).\n"
    "# To review: flip a `pending` row to `reviewed` with a confirmed `siren` + `reviewed_by`/\n"
    "# `reviewed_at` (preserved on re-seed). See data/crosswalk/README.md for the full process.\n"
)

_DEFAULT_CROSSWALK_PATH = (
    Path(__file__).resolve().parents[4] / "data" / "crosswalk" / "operateurs.yaml"
)
CROSSWALK_PATH = Path(os.environ.get("CFP_CROSSWALK_PATH", _DEFAULT_CROSSWALK_PATH))

# Curated tutelle-ministry reference: maps an operator's tutelle (a ministry code or name) to the
# ministry's own SIREN, so FSC-25 can anchor `ministry -> operator` tutelle edges. Same YAML
# conventions + governance as the crosswalk; here a row's `tutelle` field holds the ministry's own
# code (the value operators reference) and `denomination` its canonical name.
_DEFAULT_MINISTERES_PATH = (
    Path(__file__).resolve().parents[4] / "data" / "crosswalk" / "ministeres.yaml"
)
MINISTERES_PATH = Path(os.environ.get("CFP_MINISTERES_PATH", _DEFAULT_MINISTERES_PATH))

# Curated LOLF-mission -> tutelle-ministry-code reference (FSC-56). The live Jaune records an
# operator's supervision as a mission, not a ministry code; this maps the mission to its lead
# ministry's code (which `ministeres.yaml` resolves to a SIREN). Same governance as the crosswalks.
_DEFAULT_MISSIONS_PATH = (
    Path(__file__).resolve().parents[4] / "data" / "crosswalk" / "missions.yaml"
)
MISSIONS_PATH = Path(os.environ.get("CFP_MISSIONS_PATH", _DEFAULT_MISSIONS_PATH))

# Fields persisted per entry, in stable order. ``normalized_name`` is derived (not persisted):
# the denomination is the source of truth, so writing the key back would only invite drift.
_ENTRY_FIELDS = (
    "denomination",
    "status",
    "siren",
    "tutelle",
    "candidate_sirens",
    "top_match_ratio",
    "source",
    "reviewed_by",
    "reviewed_at",
    "notes",
)


def load_entries(path: Path | str = CROSSWALK_PATH) -> list[CrosswalkEntry]:
    """Parse every row into a validated :class:`CrosswalkEntry` (fails loud on bad data)."""
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: top-level YAML must be a mapping, got {type(data).__name__}")
    version = data.get("schema_version")
    if version != SCHEMA_VERSION:
        raise ValueError(
            f"{path}: unsupported schema_version {version!r}, expected {SCHEMA_VERSION}"
        )
    rows = data.get("entries", [])
    if not isinstance(rows, list):
        raise ValueError(f"{path}: 'entries' must be a list, got {type(rows).__name__}")
    return [CrosswalkEntry(**row) for row in rows]


def load_crosswalk(path: Path | str = CROSSWALK_PATH) -> Crosswalk:
    """Build a :class:`Crosswalk` from the file (collision detection fails loud)."""
    return Crosswalk.from_entries(load_entries(path))


def load_ministries(path: Path | str = MINISTERES_PATH) -> list[CrosswalkEntry]:
    """Load the reviewed ministry reference. Each row must be an accepted (SIREN-carrying) entry
    with a non-empty tutelle code; fails loud on a missing or duplicate code so an operator's
    tutelle can never silently resolve to the wrong ministry (golden rule #5)."""
    entries = load_entries(path)
    seen: dict[str, str] = {}
    for entry in entries:
        if entry.status is not CrosswalkStatus.reviewed:
            raise ValueError(
                f"{path}: ministry {entry.denomination!r} must be 'reviewed' "
                f"(hand-curated, never generated); got {entry.status.value!r}"
            )
        # Normalize the code the same way MinistryIndex looks it up (.upper()), so a case-variant
        # duplicate (e.g. 'aa' vs 'AA') fails loud here instead of silently overwriting in the
        # index and mis-resolving a tutelle.
        code = (entry.tutelle or "").strip().upper()
        if not code:
            raise ValueError(
                f"{path}: ministry {entry.denomination!r} has no tutelle code "
                "(the value operators reference)"
            )
        if entry.siren is None:
            raise ValueError(f"{path}: ministry {entry.denomination!r} must carry a SIREN")
        if code in seen:
            raise ValueError(
                f"{path}: duplicate ministry tutelle code {code!r} "
                f"({seen[code]!r} vs {entry.denomination!r})"
            )
        seen[code] = entry.denomination
    return entries


def load_missions(path: Path | str = MISSIONS_PATH) -> dict[str, str]:
    """Load the reviewed mission -> ministry-code map (FSC-56).

    Returns ``{mission_label: ministry_code}`` keyed by the *raw* mission label (the operators
    transform normalizes for lookup). Fails loud on a malformed file, a blank mission/code, or a
    duplicate mission, so an operator's mission can never silently resolve to the wrong ministry
    (golden rule #5). The referenced codes are validated against ``ministeres.yaml`` by the caller.
    """
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: top-level YAML must be a mapping, got {type(data).__name__}")
    if data.get("schema_version") != SCHEMA_VERSION:
        raise ValueError(
            f"{path}: unsupported schema_version {data.get('schema_version')!r}, "
            f"expected {SCHEMA_VERSION}"
        )
    rows = data.get("missions", [])
    if not isinstance(rows, list):
        raise ValueError(f"{path}: 'missions' must be a list, got {type(rows).__name__}")
    out: dict[str, str] = {}
    for row in rows:
        mission = str((row or {}).get("mission") or "").strip()
        code = str((row or {}).get("tutelle") or "").strip()
        if not mission or not code:
            raise ValueError(f"{path}: every mission row needs a non-empty 'mission' + 'tutelle'")
        if mission in out:
            raise ValueError(f"{path}: duplicate mission {mission!r}")
        out[mission] = code
    return out


def _entry_to_row(entry: CrosswalkEntry) -> dict[str, Any]:
    """Serialize an entry to a YAML row, dropping empty optionals for a clean diff."""
    row = entry.model_dump(mode="json", include=set(_ENTRY_FIELDS))
    ordered: dict[str, Any] = {}
    for field in _ENTRY_FIELDS:
        value = row.get(field)
        # Drop only genuinely-absent optionals. Never use falsy/equality-membership here: a
        # meaningful 0 / 0.0 (e.g. top_match_ratio=0.0) must survive the round-trip.
        if value is None or (isinstance(value, list) and not value) or value == "":
            continue
        ordered[field] = value
    return ordered


def dump_entries(
    entries: list[CrosswalkEntry], path: Path | str, *, maintainer: str | None = None
) -> None:
    """Write entries to YAML, sorted by key for byte-stable diffs across regenerations."""
    ordered = sorted(entries, key=lambda e: e.normalized_name)
    doc: dict[str, Any] = {"schema_version": SCHEMA_VERSION}
    if maintainer:
        doc["maintainer"] = maintainer
    doc["entries"] = [_entry_to_row(e) for e in ordered]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_HEADER)
        yaml.safe_dump(doc, fh, allow_unicode=True, sort_keys=False, default_flow_style=False)


# --------------------------------------------------------------------------- #
# Seed generator — transform a resolver-spike CSV into crosswalk entries (merge-aware)
# --------------------------------------------------------------------------- #
_SEED_REQUIRED_COLUMNS = ("operateur", "tier")


def _parse_ratio(raw: str) -> float | None:
    """Parse a ``top_match_ratio`` cell to a finite ratio in [0, 1], else fail loud."""
    raw = raw.strip()
    if not raw:
        return None
    try:
        value = float(raw)
    except ValueError as exc:
        raise ValueError(f"top_match_ratio is not a number: {raw!r}") from exc
    if not math.isfinite(value) or not 0.0 <= value <= 1.0:
        raise ValueError(f"top_match_ratio must be a finite ratio in [0, 1], got {raw!r}")
    return value


def row_to_seed_entry(row: dict[str, str]) -> CrosswalkEntry:
    """Map one ``operator_resolution.csv`` row (spike output) to a crosswalk entry.

    ``unique`` -> ``auto`` (reproducible exact match) with its chosen SIREN; ``multiple``/``none``
    -> ``pending`` backlog rows carrying candidate SIRENs + the difflib ratio as reviewer hints.
    """
    tier = (row.get("tier") or "").strip()
    candidates = [s for s in (row.get("candidate_sirens") or "").split("|") if s]
    ratio = _parse_ratio(row.get("top_match_ratio") or "")
    tutelle = (row.get("tutelle") or "").strip() or None
    if tier == "unique":
        return CrosswalkEntry(
            denomination=row["operateur"],
            status=CrosswalkStatus.auto,
            siren=(row.get("chosen_siren") or "").strip() or None,
            tutelle=tutelle,
            top_match_ratio=ratio,
            source="spike-auto",
        )
    return CrosswalkEntry(
        denomination=row["operateur"],
        status=CrosswalkStatus.pending,
        tutelle=tutelle,
        candidate_sirens=candidates,
        top_match_ratio=ratio,
        source="spike-backlog",
    )


def load_seed_csv(path: Path | str) -> list[CrosswalkEntry]:
    """Read a resolver-spike CSV into seed entries, failing loud on a missing required column."""
    with open(path, encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        headers = set(reader.fieldnames or ())
        missing = [c for c in _SEED_REQUIRED_COLUMNS if c not in headers]
        if missing:
            raise ValueError(
                f"{path}: seed CSV missing required column(s) {missing}; got {reader.fieldnames}"
            )
        return [row_to_seed_entry(row) for row in reader]


def merge_seed(seed: list[CrosswalkEntry], existing: list[CrosswalkEntry]) -> list[CrosswalkEntry]:
    """Merge freshly-seeded rows over existing ones, **preserving human-reviewed/category rows**.

    Regeneration must never clobber curation: any existing ``reviewed`` or ``category`` row wins
    over a seed row for the same key; otherwise the seed (auto/pending) replaces it.
    """
    curated = {e.normalized_name: e for e in existing if e.status in CURATED_STATUSES}
    merged: dict[str, CrosswalkEntry] = {e.normalized_name: e for e in seed}
    merged.update(curated)  # curated rows take precedence
    return sorted(merged.values(), key=lambda e: e.normalized_name)
