"""Load and (re)generate the reviewed entity crosswalk YAML. The I/O half of FSC-23.

The crosswalk *logic* is pure and lives in ``core.crosswalk``; this module is the only place that
touches the file. It mirrors ``registry.py``: a default path under ``data/crosswalk/`` with a
``CFP_CROSSWALK_PATH`` env override for non-editable installs. Loading fails loud — a malformed
SIREN, a broken status<->SIREN invariant, or a conflicting-key collision all raise.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml
from core.crosswalk import Crosswalk, CrosswalkEntry, CrosswalkStatus

SCHEMA_VERSION = 1

# Written at the top of the generated file so it stays self-describing across regenerations
# (yaml.safe_dump drops comments, so this header is re-emitted each time, not hand-maintained).
_HEADER = (
    "# Reviewed crosswalk: name -> SIREN for entities lacking one (golden rule #5).\n"
    "# `auto`/`pending` rows are GENERATED by `make resolve-seed` (re-seedable, merge-aware).\n"
    "# To review: flip a `pending` row to `reviewed` with a confirmed `siren` + `reviewed_by`/\n"
    "# `reviewed_at` (preserved on re-seed). See data/crosswalk/README.md for the full process.\n"
)

_DEFAULT_CROSSWALK_PATH = (
    Path(__file__).resolve().parents[4] / "data" / "crosswalk" / "operateurs.yaml"
)
CROSSWALK_PATH = Path(os.environ.get("CFP_CROSSWALK_PATH", _DEFAULT_CROSSWALK_PATH))

# Fields persisted per entry, in stable order. ``normalized_name`` is derived (not persisted):
# the denomination is the source of truth, so writing the key back would only invite drift.
_ENTRY_FIELDS = (
    "denomination",
    "status",
    "siren",
    "tutelle",
    "candidate_sirens",
    "top_match_ratio",
    "source",
    "reviewed_by",
    "reviewed_at",
    "notes",
)


def load_entries(path: Path | str = CROSSWALK_PATH) -> list[CrosswalkEntry]:
    """Parse every row into a validated :class:`CrosswalkEntry` (fails loud on bad data)."""
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    rows = data.get("entries", [])
    if not isinstance(rows, list):
        raise ValueError(f"{path}: 'entries' must be a list, got {type(rows).__name__}")
    return [CrosswalkEntry(**row) for row in rows]


def load_crosswalk(path: Path | str = CROSSWALK_PATH) -> Crosswalk:
    """Build a :class:`Crosswalk` from the file (collision detection fails loud)."""
    return Crosswalk.from_entries(load_entries(path))


def _entry_to_row(entry: CrosswalkEntry) -> dict[str, Any]:
    """Serialize an entry to a YAML row, dropping empty optionals for a clean diff."""
    row = entry.model_dump(mode="json", include=set(_ENTRY_FIELDS))
    ordered: dict[str, Any] = {}
    for field in _ENTRY_FIELDS:
        value = row.get(field)
        if value in (None, [], ""):
            continue
        ordered[field] = value
    return ordered


def dump_entries(
    entries: list[CrosswalkEntry], path: Path | str, *, maintainer: str | None = None
) -> None:
    """Write entries to YAML, sorted by key for byte-stable diffs across regenerations."""
    ordered = sorted(entries, key=lambda e: e.normalized_name)
    doc: dict[str, Any] = {"schema_version": SCHEMA_VERSION}
    if maintainer:
        doc["maintainer"] = maintainer
    doc["entries"] = [_entry_to_row(e) for e in ordered]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_HEADER)
        yaml.safe_dump(doc, fh, allow_unicode=True, sort_keys=False, default_flow_style=False)


# --------------------------------------------------------------------------- #
# Seed generator — transform a resolver-spike CSV into crosswalk entries (merge-aware)
# --------------------------------------------------------------------------- #
def _row_to_seed_entry(row: dict[str, str]) -> CrosswalkEntry:
    """Map one ``operator_resolution.csv`` row (spike output) to a crosswalk entry.

    ``unique`` -> ``auto`` (reproducible exact match) with its chosen SIREN; ``multiple``/``none``
    -> ``pending`` backlog rows carrying candidate SIRENs + the difflib ratio as reviewer hints.
    """
    tier = (row.get("tier") or "").strip()
    candidates = [s for s in (row.get("candidate_sirens") or "").split("|") if s]
    ratio_raw = (row.get("top_match_ratio") or "").strip()
    ratio = float(ratio_raw) if ratio_raw else None
    tutelle = (row.get("tutelle") or "").strip() or None
    if tier == "unique":
        return CrosswalkEntry(
            denomination=row["operateur"],
            status=CrosswalkStatus.auto,
            siren=(row.get("chosen_siren") or "").strip() or None,
            tutelle=tutelle,
            top_match_ratio=ratio,
            source="spike-auto",
        )
    return CrosswalkEntry(
        denomination=row["operateur"],
        status=CrosswalkStatus.pending,
        tutelle=tutelle,
        candidate_sirens=candidates,
        top_match_ratio=ratio,
        source="spike-backlog",
    )


def merge_seed(seed: list[CrosswalkEntry], existing: list[CrosswalkEntry]) -> list[CrosswalkEntry]:
    """Merge freshly-seeded rows over existing ones, **preserving human-reviewed/category rows**.

    Regeneration must never clobber curation: any existing ``reviewed`` or ``category`` row wins
    over a seed row for the same key; otherwise the seed (auto/pending) replaces it.
    """
    curated = {
        e.normalized_name: e
        for e in existing
        if e.status in (CrosswalkStatus.reviewed, CrosswalkStatus.category)
    }
    merged: dict[str, CrosswalkEntry] = {e.normalized_name: e for e in seed}
    merged.update(curated)  # curated rows take precedence
    return sorted(merged.values(), key=lambda e: e.normalized_name)
